title: Nidin Shah Ryidhzuan
logo: /assets/img/headshot_circle.png
description: API Specialist, Cloud, and Data Analytics enthusiast
show_downloads: false
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag
